services:
  rabbit:
    image: rabbitmq:3.11-management-alpine
    restart: unless-stopped
    networks:
      - app
      - frontend
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
      - "RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}"

  supervisor:
    image: itkdev/supervisor-php8.1:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 async_priority_high
      - APP_SUPERVISOR_WORKERS=1
      - APP_SUPERVISOR_USER=deploy
      - PHP_APCU_ENABLED=1
      - PHP_APCU_ENABLED_CLI=1
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "selvbetjening.aarhuskommune.dk:40.127.143.145"
    volumes:
      - .:/app

  phpfpm:
    environment:
      - PHP_APCU_ENABLED=1
      - PHP_APCU_ENABLED_CLI=1
      - PHP_MEMORY_LIMIT=256M

  # Build container for frontend assets
  node:
    user: '1042'
    image: node:18
    networks:
      - app
    working_dir: /app
    environment:
      - NODE_ENV=prod
      - npm_config_cache=/app/.npm
    volumes:
      - .:/app